import type { FeedType } from '../types/userSettings'

export interface FeedTypeSelectorProps {
  currentFeedType: FeedType
  onFeedTypeChange: (feedType: FeedType) => void
  isPending: boolean
  isError: boolean
}

export function FeedTypeSelector({
  currentFeedType,
  onFeedTypeChange,
  isPending,
  isError,
}: FeedTypeSelectorProps) {
  function handleChange(event: React.ChangeEvent<HTMLSelectElement>) {
    onFeedTypeChange(event.target.value as FeedType)
  }

  return (
    <div>
      <label
        htmlFor="feed-type-select"
        className="mb-1 block text-xs text-[var(--color-text-muted)]"
      >
        Market Feed Type
      </label>
      <div className="flex items-center gap-2">
        <select
          id="feed-type-select"
          value={currentFeedType}
          onChange={handleChange}
          disabled={isPending}
          aria-busy={isPending}
          className="text-xs text-[var(--color-text-primary)] disabled:opacity-50"
        >
          <option
            value="SYNTHETIC"
            title="Market data generated by the platform, used for testing and playing around."
          >
            Synthetic Feed
          </option>
          <option
            value="REAL"
            title="Market data obtained from real trading platforms."
          >
            Real Market Feed
          </option>
        </select>
        {isPending && (
          <span className="text-xs text-[var(--color-text-muted)]" aria-label="Saving">
            Saving…
          </span>
        )}
      </div>
      {isError && (
        <p className="mt-1 text-xs text-red-500" role="alert">
          Failed to save. Please try again.
        </p>
      )}
    </div>
  )
}
