import { describe, it, expect, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import { userEvent } from '@testing-library/user-event'
import { FeedTypeSelector } from './FeedTypeSelector'

describe('FeedTypeSelector', () => {
  it('FeedTypeSelector - renders current value selected', () => {
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={vi.fn()}
        isPending={false}
        isError={false}
        errorStatus={null}
      />,
    )
    const select = screen.getByRole('combobox')
    expect((select as HTMLSelectElement).value).toBe('SYNTHETIC')
  })

  it('FeedTypeSelector - renders both options with correct labels', () => {
    render(
      <FeedTypeSelector
        currentFeedType="REAL"
        onFeedTypeChange={vi.fn()}
        isPending={false}
        isError={false}
        errorStatus={null}
      />,
    )
    expect(screen.getByRole('option', { name: 'Synthetic Feed' })).toBeInTheDocument()
    expect(screen.getByRole('option', { name: 'Real Market Feed' })).toBeInTheDocument()
  })

  it('FeedTypeSelector - SYNTHETIC option has correct tooltip', () => {
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={vi.fn()}
        isPending={false}
        isError={false}
        errorStatus={null}
      />,
    )
    const syntheticOption = screen.getByRole('option', { name: 'Synthetic Feed' })
    expect(syntheticOption).toHaveAttribute(
      'title',
      'Market data generated by the platform, used for testing and playing around.',
    )
  })

  it('FeedTypeSelector - REAL option has correct tooltip', () => {
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={vi.fn()}
        isPending={false}
        isError={false}
        errorStatus={null}
      />,
    )
    const realOption = screen.getByRole('option', { name: 'Real Market Feed' })
    expect(realOption).toHaveAttribute(
      'title',
      'Market data obtained from real trading platforms.',
    )
  })

  it('FeedTypeSelector - calls onFeedTypeChange on selection', async () => {
    const onFeedTypeChange = vi.fn()
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={onFeedTypeChange}
        isPending={false}
        isError={false}
        errorStatus={null}
      />,
    )
    const user = userEvent.setup()
    await user.selectOptions(screen.getByRole('combobox'), 'REAL')
    expect(onFeedTypeChange).toHaveBeenCalledWith('REAL')
  })

  it('FeedTypeSelector - is disabled when isPending is true', () => {
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={vi.fn()}
        isPending={true}
        isError={false}
        errorStatus={null}
      />,
    )
    expect(screen.getByRole('combobox')).toBeDisabled()
  })

  it('FeedTypeSelector - shows loading indicator when isPending is true', () => {
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={vi.fn()}
        isPending={true}
        isError={false}
        errorStatus={null}
      />,
    )
    expect(screen.getByLabelText('Saving')).toBeInTheDocument()
  })

  it('FeedTypeSelector - shows specific error message on 400', () => {
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={vi.fn()}
        isPending={false}
        isError={true}
        errorStatus={400}
      />,
    )
    expect(screen.getByRole('alert')).toHaveTextContent('Invalid feed type selected.')
  })

  it('FeedTypeSelector - shows generic error message on 500', () => {
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={vi.fn()}
        isPending={false}
        isError={true}
        errorStatus={500}
      />,
    )
    expect(screen.getByRole('alert')).toHaveTextContent('Failed to save. Please try again.')
  })

  it('FeedTypeSelector - shows generic error message on 403', () => {
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={vi.fn()}
        isPending={false}
        isError={true}
        errorStatus={403}
      />,
    )
    expect(screen.getByRole('alert')).toHaveTextContent('Failed to save. Please try again.')
  })

  it('FeedTypeSelector - does not show error message when isError is false', () => {
    render(
      <FeedTypeSelector
        currentFeedType="SYNTHETIC"
        onFeedTypeChange={vi.fn()}
        isPending={false}
        isError={false}
        errorStatus={null}
      />,
    )
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
  })
})
