import type { FeedType } from '../types/userSettings'
import { Label } from '@/shared/components/ui/label'
import { Alert, AlertDescription } from '@/shared/components/ui/alert'

export interface FeedTypeSelectorProps {
  currentFeedType: FeedType
  onFeedTypeChange: (feedType: FeedType) => void
  isPending: boolean
  isError: boolean
  /** HTTP status code of the last failed mutation, or null if no error. */
  errorStatus: number | null
}

export function FeedTypeSelector({
  currentFeedType,
  onFeedTypeChange,
  isPending,
  isError,
  errorStatus,
}: FeedTypeSelectorProps) {
  function handleChange(event: React.ChangeEvent<HTMLSelectElement>) {
    onFeedTypeChange(event.target.value as FeedType)
  }

  const errorMessage =
    isError
      ? errorStatus === 400
        ? 'Invalid feed type selected.'
        : 'Failed to save. Please try again.'
      : null

  return (
    <div className="flex flex-col gap-1.5">
      <Label htmlFor="feed-type-select">Market Feed Type</Label>
      <div className="flex items-center gap-2">
        <select
          id="feed-type-select"
          value={currentFeedType}
          onChange={handleChange}
          disabled={isPending}
          aria-busy={isPending}
          className="flex h-8 rounded border border-[hsl(var(--border))] bg-transparent px-3 py-1 text-xs text-[hsl(var(--foreground))] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[hsl(var(--ring))] disabled:cursor-not-allowed disabled:opacity-50"
        >
          <option
            value="SYNTHETIC"
            title="Market data generated by the platform, used for testing and playing around."
          >
            Synthetic Feed
          </option>
          <option
            value="REAL"
            title="Market data obtained from real trading platforms."
          >
            Real Market Feed
          </option>
        </select>
        {isPending && (
          <span className="text-xs text-[var(--color-text-muted)]" aria-label="Saving">
            Saving…
          </span>
        )}
      </div>
      {errorMessage && (
        <Alert variant="destructive" role="alert" className="mt-1">
          <AlertDescription>{errorMessage}</AlertDescription>
        </Alert>
      )}
    </div>
  )
}
